.nh
.TH "LMM" "1" "Jul 2026" "lmm 1.28.0" "User Commands"

.SH NAME
lmm-completion-bash - Generate the autocompletion script for bash


.SH SYNOPSIS
\fBlmm completion bash\fP


.SH DESCRIPTION
Generate the autocompletion script for the bash shell.

.PP
This script depends on the 'bash-completion' package.
If it is not installed already, you can install it via your OS's package manager.

.PP
To load completions in your current shell session:

.EX
source <(lmm completion bash)
.EE

.PP
To load completions for every new session, execute once:

.SS Linux:
.EX
lmm completion bash > /etc/bash_completion.d/lmm
.EE

.SS macOS:
.EX
lmm completion bash > $(brew --prefix)/etc/bash_completion.d/lmm
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bash

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config directory (default: ~/.config/lmm)

.PP
\fB--data\fP=""
	data directory (default: ~/.local/share/lmm)

.PP
\fB-g\fP, \fB--game\fP=""
	game ID to operate on

.PP
\fB--json\fP[=false]
	output in JSON format (list, status, search, update, conflicts, verify, mod show, source list)

.PP
\fB--no-color\fP[=false]
	disable colored output (NO_COLOR env is also honored)

.PP
\fB--no-hooks\fP[=false]
	disable all hooks

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBlmm-completion(1)\fP


.SH HISTORY
27-Jul-2026 Auto generated by spf13/cobra
