.nh
.TH "LMM" "1" "Jul 2026" "lmm 1.29.1" "User Commands"

.SH NAME
lmm-purge - Remove all deployed mods from game directory


.SH SYNOPSIS
\fBlmm purge [flags]\fP


.SH DESCRIPTION
Remove all deployed mod files from the game directory.

.PP
This command undeploys all mods, essentially resetting the game directory
back to its pre-modded state. Use this when mods get out of sync or you
want to start fresh.

.PP
Mod records are preserved in the database, so you can deploy them later
with 'lmm deploy'. Use --uninstall to also remove the database records.

.PP
Examples:
  lmm purge --game skyrim-se
  lmm purge --game skyrim-se --profile survival
  lmm purge --game skyrim-se --uninstall
  lmm purge --game skyrim-se --yes


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	continue even if hooks fail

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for purge

.PP
\fB-p\fP, \fB--profile\fP=""
	profile to purge (default: active profile)

.PP
\fB--uninstall\fP[=false]
	also remove mod records from database (like uninstalling each mod)

.PP
\fB-y\fP, \fB--yes\fP[=false]
	skip confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config directory (default: ~/.config/lmm)

.PP
\fB--data\fP=""
	data directory (default: ~/.local/share/lmm)

.PP
\fB-g\fP, \fB--game\fP=""
	game ID to operate on

.PP
\fB--json\fP[=false]
	output in JSON format (list, status, search, update, conflicts, verify, mod show, source list, game list)

.PP
\fB--no-color\fP[=false]
	disable colored output (NO_COLOR env is also honored)

.PP
\fB--no-hooks\fP[=false]
	disable all hooks

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBlmm(1)\fP


.SH HISTORY
27-Jul-2026 Auto generated by spf13/cobra
