.nh
.TH "LMM" "1" "Jul 2026" "lmm 1.20.0" "User Commands"

.SH NAME
lmm-mod-set-update - Set update policy for a mod


.SH SYNOPSIS
\fBlmm mod set-update  [flags]\fP


.SH DESCRIPTION
Set the update policy for an installed mod.

.PP
Policies:
  --auto    Automatically apply updates when checking
  --notify  Show available updates, require manual approval (default)
  --pin     Never update this mod automatically

.PP
Examples:
  lmm mod set-update 12345 --game skyrim-se --auto
  lmm mod set-update 12345 --game skyrim-se --pin
  lmm mod set-update 12345 --game skyrim-se --notify


.SH OPTIONS
\fB--auto\fP[=false]
	enable auto-update

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set-update

.PP
\fB--notify\fP[=false]
	notify only (default)

.PP
\fB--pin\fP[=false]
	pin to current version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config directory (default: ~/.config/lmm)

.PP
\fB--data\fP=""
	data directory (default: ~/.local/share/lmm)

.PP
\fB-g\fP, \fB--game\fP=""
	game ID to operate on

.PP
\fB--json\fP[=false]
	output in JSON format (list, status, search, update, conflicts, verify, mod show, source list)

.PP
\fB--no-color\fP[=false]
	disable colored output

.PP
\fB--no-hooks\fP[=false]
	disable all hooks

.PP
\fB-p\fP, \fB--profile\fP=""
	profile (default: active profile)

.PP
\fB-s\fP, \fB--source\fP=""
	mod source (default: first configured source alphabetically)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBlmm-mod(1)\fP


.SH HISTORY
27-Jul-2026 Auto generated by spf13/cobra
