.nh
.TH "LMM" "1" "Jul 2026" "lmm 2.0.0" "User Commands"

.SH NAME
lmm-completion-zsh - Generate the autocompletion script for zsh


.SH SYNOPSIS
\fBlmm completion zsh [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the zsh shell.

.PP
If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:

.EX
echo "autoload -U compinit; compinit" >> ~/.zshrc
.EE

.PP
To load completions in your current shell session:

.EX
source <(lmm completion zsh)
.EE

.PP
To load completions for every new session, execute once:

.SS Linux:
.EX
lmm completion zsh > "${fpath[1]}/_lmm"
.EE

.SS macOS:
.EX
lmm completion zsh > $(brew --prefix)/share/zsh/site-functions/_lmm
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for zsh

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config directory (default: $XDG_CONFIG_HOME/lmm or ~/.config/lmm)

.PP
\fB--data\fP=""
	data directory (default: $XDG_DATA_HOME/lmm or ~/.local/share/lmm)

.PP
\fB-g\fP, \fB--game\fP=""
	game ID to operate on

.PP
\fB--json\fP[=false]
	output JSON instead of text; mutating commands print their result, --dry-run prints the plan; never prompts

.PP
\fB--log-level\fP="off"
	diagnostic log level written to stderr (off, error, warn, info, debug)

.PP
\fB--no-color\fP[=false]
	disable colored output (NO_COLOR env is also honored)

.PP
\fB--no-hooks\fP[=false]
	disable all hooks

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBlmm-completion(1)\fP


.SH HISTORY
27-Jul-2026 Auto generated by spf13/cobra
